name: 'Allure Report with history'
description: 'Generate Allure Report with history'
inputs:
  allure_results:
    description: 'Allure test result data dir'
    required: true
    default: 'allure-results'
  allure_report:
    description: 'Allure report target dir'
    required: true
    default: 'allure-report'
  allure_version:
    description: 'Allure commandline version'
    required: true
    default: ${{ github.run_number }}
  gh_pages:
    description: 'Folder with gh-pages branch'
    required: true
    default: 'gh-pages'
  allure_history:
    description: 'Folder for allure history'
    required: true
    default: 'allure-history'
  github_pages_url:
    description: 'GitHub Pages URL'
    required: true
    default: 'github.com'
runs:
  using: 'docker'
  image: 'Dockerfile'
  #args:
  #  - ${{ inputs.results-dir }}
  #  - ${{ inputs.report-dir }}
  #  - ${{ inputs.allure-version }}