name: allure-javascript

on:
  push:
    branches-ignore:
      - 'gh-pages'
    paths:
      - 'allure-javascript/**'
      - '**/allure-javascript.yml'

jobs:
  codeceptjs:
    name: Push to repo allure-javascript-codeceptjs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Copy needed files
        run: |
          mkdir -p result
          cp -r ${{ github.workflow }}/${{ github.workflow }}-codeceptjs/. ./result
          mkdir -p ./result/.github/workflows
          cp ${{ github.workflow }}/.github/workflows/${{ github.workflow }}-codeceptjs.yml ./result/.github/workflows
          ls -l result

      - run: git init
        working-directory: result

      - name: Push
        uses: actions-js/push@master
        with:
          repository: allure-examples/${{ github.workflow }}-codeceptjs
          directory: result
          message: ${{ github.event.head_commit.message }}
          force: true
          github_token: ${{ secrets.QAMETA_TOKEN }}

  cucumberjs:
    name: Push to repo allure-javascript-cucumberjs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Copy needed files
        run: |
          mkdir -p result
          cp -r ${{ github.workflow }}/${{ github.workflow }}-cucumberjs/. ./result
          mkdir -p ./result/.github/workflows
          cp ${{ github.workflow }}/.github/workflows/${{ github.workflow }}-cucumberjs.yml ./result/.github/workflows
          ls -l result

      - run: git init
        working-directory: result

      - name: Push
        uses: actions-js/push@master
        with:
          repository: allure-examples/${{ github.workflow }}-cucumberjs
          directory: result
          message: ${{ github.event.head_commit.message }}
          force: true
          github_token: ${{ secrets.QAMETA_TOKEN }}

  jest:
    name: Push to repo allure-javascript-jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Copy needed files
        run: |
          mkdir -p result
          cp -r ${{ github.workflow }}/${{ github.workflow }}-jest/. ./result
          mkdir -p ./result/.github/workflows
          cp ${{ github.workflow }}/.github/workflows/${{ github.workflow }}-jest.yml ./result/.github/workflows
          ls -l result

      - run: git init
        working-directory: result

      - name: Push
        uses: actions-js/push@master
        with:
          repository: allure-examples/${{ github.workflow }}-jest
          directory: result
          message: ${{ github.event.head_commit.message }}
          force: true
          github_token: ${{ secrets.QAMETA_TOKEN }}