name: allure-java-commons

on:
  push:
    branches-ignore:
      - 'gh-pages'
    paths:
    - 'allure-java-commons/**'
    - '**/allure-java-commons.yml'

jobs:
  gradle-kts:
    name: Push to repo ...-gradle-kts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Copy needed files
        run: |
          mkdir -p result
          cp -r ${{ github.workflow }}/src/. ./result/src
          cp -r ${{ github.workflow }}/gradle/. ./result/gradle
          cp ${{ github.workflow }}/gradlew ./result
          cp ${{ github.workflow }}/gradlew.bat ./result
          cp ${{ github.workflow }}/build.gradle.kts ./result
          cp ${{ github.workflow }}/README.md ./result
          mkdir -p ./result/.github/workflows
          cp ${{ github.workflow }}/.github/workflows/${{ github.workflow }}.yml ./result/.github/workflows
          ls -l result

      - run: git init
        working-directory: result

      - name: Push
        uses: actions-js/push@master
        with:
          repository: allure-examples/${{ github.workflow }}
          directory: result
          message: ${{ github.event.head_commit.message }}
          force: true
          github_token: ${{ secrets.QAMETA_TOKEN }}