name: java-junit5

on:
  push:
    branches-ignore:
      - 'gh-pages'
    paths:
    - 'java-junit5/**'
    - '**/java-junit5.yml'

env:
  working_dir: ${{ github.workflow }}

jobs:
  gradle-kts:
    name: Push to repo java-junit5-gradle-kts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          #path: ${{ env.working_dir }}
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          #fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Copy needed files
        run: |
          cp -r ${{ env.working_dir }}/. ./gradle-kts
          rm ./gradle-kts/build.gradle ./gradle-kts/pom.xml

## mkdir -p ./gradle-kts/.github/workflows && cp -r ./.github/workflows/${{ env.working_dir }}-gradle-kts.yml "$_"

      - run: ls -l gradle-kts

      - run: git init
        working-directory: gradle-kts

      - name: Push
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          force: true
          directory: gradle-kts
          repository: simple-elf/java-junit5-gradle-kts