name: maven-junit5

on:
  push:
    branches-ignore:
      - '!master'
    #paths:
    #- 'maven-junit5/**'
    #- '**/maven-junit5.yml'

env:
  working_dir: ${{ github.workflow }}

jobs:
  autotests:
    name: Generate Allure Report
    runs-on: ubuntu-latest
    defaults:
      run:
        #shell: bash
        working-directory: ${{ env.working_dir }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: |
            ~/.m2/repository
          #  ~/.gradle/caches
          key: ${{ runner.os }}-${{ env.working_dir }}-${{ hashFiles('maven-junit5/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.working_dir }}-

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install dependencies
        run: mvn dependency:go-offline compile compiler:testCompile

      - name: Run Test
        if: always()
        run: mvn test
        continue-on-error: true

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Test local action
        uses: ./allure-report-action
        if: always()
        #id: allure-report
        with:
          allure_results: ${{ env.working_dir }}/target/allure-results
          #gh_pages: gh-pages
          #allure_report: allure-report
          allure_history: allure-history
          subfolder: "/${{ env.working_dir }}"

      - run: mv $(pwd)/../index.html $(pwd)/allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

      #- uses: actions/upload-artifact@master
      #  with:
      #    name: allure-report
      #    path: allure-report